#spring.datasource.name=dev
#spring.datasource.url=jdbc:mysql://10.104.20.123:3306/qtccloud
#spring.datasource.username=developer
#spring.datasource.password=developer1015
server:
  port: 6602

spring:
  application:
    name: configcenter
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xdota3310/config-center.git
          clone-on-start: true
          #https://github.com/xdota3310/sjsite-cloud.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:6601/eureka/
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}







#eureka
# client
#  service-url.defaultZone=http://${spring.cloud.client.ip-address}:8001/eureka/
#eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
#
#spring.redis.host=10.104.10.14
#spring.redis.port=6379
##spring.redis.password=123456
#spring.redis.database=0
#spring.redis.timeout=PT0S
#
#metaq.consumer.start-up=true
#
##彩色日志
#spring.output.ansi.enabled=ALWAYS
#
##openoffice
#openOffice.host=10.104.108.177
#openOffice.port=8100
