server:
  port: 6611

spring:
  application:
    name: blog

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:6601/eureka/
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}