server:
  port: 6601

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}

  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 5000

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/